
// @ts-ignore;
import React, { useState, useRef, useEffect, forwardRef } from 'react';
// @ts-ignore;
import { Button, Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui';
// @ts-ignore;
import { ChevronDown, X, MapPin } from 'lucide-react';

// 完整的中国行政区划数据
const chinaRegions = {
  provinces: [{
    code: '11',
    name: '北京市'
  }, {
    code: '12',
    name: '天津市'
  }, {
    code: '13',
    name: '河北省'
  }, {
    code: '14',
    name: '山西省'
  }, {
    code: '15',
    name: '内蒙古自治区'
  }, {
    code: '21',
    name: '辽宁省'
  }, {
    code: '22',
    name: '吉林省'
  }, {
    code: '23',
    name: '黑龙江省'
  }, {
    code: '31',
    name: '上海市'
  }, {
    code: '32',
    name: '江苏省'
  }, {
    code: '33',
    name: '浙江省'
  }, {
    code: '34',
    name: '安徽省'
  }, {
    code: '35',
    name: '福建省'
  }, {
    code: '36',
    name: '江西省'
  }, {
    code: '37',
    name: '山东省'
  }, {
    code: '41',
    name: '河南省'
  }, {
    code: '42',
    name: '湖北省'
  }, {
    code: '43',
    name: '湖南省'
  }, {
    code: '44',
    name: '广东省'
  }, {
    code: '45',
    name: '广西壮族自治区'
  }, {
    code: '46',
    name: '海南省'
  }, {
    code: '50',
    name: '重庆市'
  }, {
    code: '51',
    name: '四川省'
  }, {
    code: '52',
    name: '贵州省'
  }, {
    code: '53',
    name: '云南省'
  }, {
    code: '54',
    name: '西藏自治区'
  }, {
    code: '61',
    name: '陕西省'
  }, {
    code: '62',
    name: '甘肃省'
  }, {
    code: '63',
    name: '青海省'
  }, {
    code: '64',
    name: '宁夏回族自治区'
  }, {
    code: '65',
    name: '新疆维吾尔自治区'
  }, {
    code: '71',
    name: '台湾省'
  }, {
    code: '81',
    name: '香港特别行政区'
  }, {
    code: '82',
    name: '澳门特别行政区'
  }],
  cities: {
    '11': [{
      code: '1101',
      name: '北京市'
    }],
    '12': [{
      code: '1201',
      name: '天津市'
    }],
    '13': [{
      code: '1301',
      name: '石家庄市'
    }, {
      code: '1302',
      name: '唐山市'
    }, {
      code: '1303',
      name: '秦皇岛市'
    }, {
      code: '1304',
      name: '邯郸市'
    }, {
      code: '1305',
      name: '邢台市'
    }, {
      code: '1306',
      name: '保定市'
    }, {
      code: '1307',
      name: '张家口市'
    }, {
      code: '1308',
      name: '承德市'
    }, {
      code: '1309',
      name: '沧州市'
    }, {
      code: '1310',
      name: '廊坊市'
    }, {
      code: '1311',
      name: '衡水市'
    }],
    '14': [{
      code: '1401',
      name: '太原市'
    }, {
      code: '1402',
      name: '大同市'
    }, {
      code: '1403',
      name: '阳泉市'
    }, {
      code: '1404',
      name: '长治市'
    }, {
      code: '1405',
      name: '晋城市'
    }, {
      code: '1406',
      name: '朔州市'
    }, {
      code: '1407',
      name: '晋中市'
    }, {
      code: '1408',
      name: '运城市'
    }, {
      code: '1409',
      name: '忻州市'
    }, {
      code: '1410',
      name: '临汾市'
    }, {
      code: '1411',
      name: '吕梁市'
    }],
    '15': [{
      code: '1501',
      name: '呼和浩特市'
    }, {
      code: '1502',
      name: '包头市'
    }, {
      code: '1503',
      name: '乌海市'
    }, {
      code: '1504',
      name: '赤峰市'
    }, {
      code: '1505',
      name: '通辽市'
    }, {
      code: '1506',
      name: '鄂尔多斯市'
    }, {
      code: '1507',
      name: '呼伦贝尔市'
    }, {
      code: '1508',
      name: '巴彦淖尔市'
    }, {
      code: '1509',
      name: '乌兰察布市'
    }, {
      code: '1522',
      name: '兴安盟'
    }, {
      code: '1525',
      name: '锡林郭勒盟'
    }, {
      code: '1529',
      name: '阿拉善盟'
    }],
    '21': [{
      code: '2101',
      name: '沈阳市'
    }, {
      code: '2102',
      name: '大连市'
    }, {
      code: '2103',
      name: '鞍山市'
    }, {
      code: '2104',
      name: '抚顺市'
    }, {
      code: '2105',
      name: '本溪市'
    }, {
      code: '2106',
      name: '丹东市'
    }, {
      code: '2107',
      name: '锦州市'
    }, {
      code: '2108',
      name: '营口市'
    }, {
      code: '2109',
      name: '阜新市'
    }, {
      code: '2110',
      name: '辽阳市'
    }, {
      code: '2111',
      name: '盘锦市'
    }, {
      code: '2112',
      name: '铁岭市'
    }, {
      code: '2113',
      name: '朝阳市'
    }, {
      code: '2114',
      name: '葫芦岛'
    }],
    '22': [{
      code: '2201',
      name: '长春市'
    }, {
      code: '2202',
      name: '吉林市'
    }, {
      code: '2203',
      name: '四平市'
    }, {
      code: '2204',
      name: '辽源市'
    }, {
      code: '2205',
      name: '通化市'
    }, {
      code: '2206',
      name: '白山市'
    }, {
      code: '2207',
      name: '松原市'
    }, {
      code: '2208',
      name: '白城市'
    }, {
      code: '2224',
      name: '延边朝鲜族自治州'
    }],
    '23': [{
      code: '2301',
      name: '哈尔滨市'
    }, {
      code: '2302',
      name: '齐齐哈尔市'
    }, {
      code: '2303',
      name: '鸡西市'
    }, {
      code: '2304',
      name: '鹤岗市'
    }, {
      code: '2305',
      name: '双鸭山市'
    }, {
      code: '2306',
      name: '大庆市'
    }, {
      code: '2307',
      name: '伊春市'
    }, {
      code: '2308',
      name: '佳木斯'
    }, {
      code: '2309',
      name: '七台河市'
    }, {
      code: '2310',
      name: '牡丹江市'
    }, {
      code: '2311',
      name: '黑河市'
    }, {
      code: '2312',
      name: '绥化市'
    }, {
      code: '2327',
      name: '大兴安岭地区'
    }],
    '31': [{
      code: '3101',
      name: '上海市'
    }],
    '32': [{
      code: '3201',
      name: '南京市'
    }, {
      code: '3202',
      name: '无锡市'
    }, {
      code: '3203',
      name: '徐州市'
    }, {
      code: '3204',
      name: '常州市'
    }, {
      code: '3205',
      name: '苏州市'
    }, {
      code: '3206',
      name: '南通市'
    }, {
      code: '3207',
      name: '连云港市'
    }, {
      code: '3208',
      name: '淮安市'
    }, {
      code: '3209',
      name: '盐城市'
    }, {
      code: '3210',
      name: '扬州市'
    }, {
      code: '3211',
      name: '镇江市'
    }, {
      code: '3212',
      name: '泰州市'
    }, {
      code: '3213',
      name: '宿迁市'
    }],
    '33': [{
      code: '3301',
      name: '杭州市'
    }, {
      code: '3302',
      name: '宁波市'
    }, {
      code: '3303',
      name: '温州市'
    }, {
      code: '3304',
      name: '嘉兴市'
    }, {
      code: '3305',
      name: '湖州市'
    }, {
      code: '3306',
      name: '绍兴市'
    }, {
      code: '3307',
      name: '金华市'
    }, {
      code: '3308',
      name: '衢州市'
    }, {
      code: '3309',
      name: '舟山市'
    }, {
      code: '3310',
      name: '台州市'
    }, {
      code: '3311',
      name: '丽水市'
    }],
    '34': [{
      code: '3401',
      name: '合肥市'
    }, {
      code: '3402',
      name: '芜湖市'
    }, {
      code: '3403',
      name: '蚌埠市'
    }, {
      code: '3404',
      name: '淮南市'
    }, {
      code: '3405',
      name: '马鞍山市'
    }, {
      code: '3406',
      name: '淮北市'
    }, {
      code: '3407',
      name: '铜陵市'
    }, {
      code: '3408',
      name: '安庆市'
    }, {
      code: '3410',
      name: '黄山市'
    }, {
      code: '3411',
      name: '滁州市'
    }, {
      code: '3412',
      name: '阜阳市'
    }, {
      code: '3413',
      name: '宿州市'
    }, {
      code: '3415',
      name: '六安市'
    }, {
      code: '3416',
      name: '亳州市'
    }, {
      code: '3417',
      name: '池州市'
    }, {
      code: '3418',
      name: '宣城市'
    }],
    '35': [{
      code: '3501',
      name: '福州市'
    }, {
      code: '3502',
      name: '厦门市'
    }, {
      code: '3503',
      name: '莆田市'
    }, {
      code: '3504',
      name: '三明市'
    }, {
      code: '3505',
      name: '泉州市'
    }, {
      code: '3506',
      name: '漳州市'
    }, {
      code: '3507',
      name: '南平市'
    }, {
      code: '3508',
      name: '龙岩市'
    }, {
      code: '3509',
      name: '宁德市'
    }],
    '36': [{
      code: '3601',
      name: '南昌市'
    }, {
      code: '3602',
      name: '景德镇市'
    }, {
      code: '3603',
      name: '萍乡市'
    }, {
      code: '3604',
      name: '九江市'
    }, {
      code: '3605',
      name: '新余市'
    }, {
      code: '3606',
      name: '鹰潭市'
    }, {
      code: '3607',
      name: '赣州市'
    }, {
      code: '3608',
      name: '吉安市'
    }, {
      code: '3609',
      name: '宜春市'
    }, {
      code: '3610',
      name: '抚州市'
    }, {
      code: '3611',
      name: '上饶市'
    }],
    '37': [{
      code: '3701',
      name: '济南市'
    }, {
      code: '3702',
      name: '青岛市'
    }, {
      code: '3703',
      name: '淄博市'
    }, {
      code: '3704',
      name: '枣庄市'
    }, {
      code: '3705',
      name: '东营市'
    }, {
      code: '3706',
      name: '烟台市'
    }, {
      code: '3707',
      name: '潍坊市'
    }, {
      code: '3708',
      name: '济宁市'
    }, {
      code: '3709',
      name: '泰安市'
    }, {
      code: '3710',
      name: '威海市'
    }, {
      code: '3711',
      name: '日照市'
    }, {
      code: '3713',
      name: '临沂市'
    }, {
      code: '3714',
      name: '德州市'
    }, {
      code: '3715',
      name: '聊城市'
    }, {
      code: '